services:
  web:
    build: .
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./BEProject.db:/app/BEProject.db
    restart: unless-stopped